[project]
name = "read"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "firebase-admin>=6.6.0",
    "pi-rc522",
    "pygame>=2.6.1",
    "requests>=2.32.3",
]

[tool.uv.sources]
pi-rc522 = { path = "../pi-rc522" }
